### ISSUE TITLE
yeoman-generator failing on the 8.3.0

### ISSUE THREAD

**Issue by al-k21** [nodejs/citgm#467] opened 2017-08-22 16:02 UTC
* **Node Version**: 8.3.0.0 
* **CitGM Version**: 2.0.5
* **Platform**: Darwin

<details> <summary>Output</summary>

  ```bash
166 passing (2s)
  8 failing

  1) Base #option() disallows Boolean options starting with no-:
     AssertionError [ERR_ASSERTION]: Missing expected exception.
      at _throws (assert.js:516:5)
      at Function.throws (assert.js:540:3)
      at Context.<anonymous> (test/base.js:682:14)

  2) Base #option() disallows Boolean options starting with no-:
     AssertionError [ERR_ASSERTION]: Missing expected exception.
      at _throws (assert.js:516:5)
      at Function.throws (assert.js:540:3)
      at Context.<anonymous> (test/base.js:682:14)

  3) Base #composeWith() runs the composed generators:
     Uncaught Error: You don’t seem to have a generator with the name “composed:gen” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-composed:gen.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
      at Environment.create (node_modules/yeoman-environment/lib/environment.js:300:7)
      at Dummy.composeWith (lib/index.js:9:19585)
      at Context.<anonymous> (test/base.js:749:18)

  4) Base #composeWith() runs the composed generators:
     Uncaught Error: You don’t seem to have a generator with the name “composed:gen” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-composed:gen.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
      at Environment.create (node_modules/yeoman-environment/lib/environment.js:300:7)
      at Dummy.composeWith (lib/index.js:9:19585)
      at Context.<anonymous> (test/base.js:749:18)

  5) Base #composeWith() when passing a local path to a generator runs the composed generator:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:798:20)

  6) Base #composeWith() when passing a local path to a generator pass options and arguments to the composed generators:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:806:20)

  7) Base #composeWith() when passing a local path to a generator pass options and arguments to the composed generators:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:806:20)

  8) Base #composeWith() when passing a local path to a generator sets correct metadata on the Generator constructor:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:815:20)



-----------------------|----------|----------|----------|----------|----------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------|----------|----------|----------|----------|----------------|
 lib/                  |    93.75 |    91.54 |    95.83 |    94.09 |                |
  index.js             |    93.75 |    91.54 |    95.83 |    94.09 |... 681,694,695 |
 lib/actions/          |    82.39 |    60.27 |    63.64 |    82.86 |                |
  help.js              |    53.33 |       20 |    33.33 |    54.55 |... 122,123,132 |
  install.js           |    93.65 |    90.32 |      100 |    93.65 |   56,60,61,157 |
  spawn-command.js     |      100 |      100 |      100 |      100 |                |
  user.js              |      100 |       75 |      100 |      100 |                |
 lib/util/             |    96.55 |    94.94 |    93.75 |    96.53 |                |
  binary-diff.js       |    95.24 |    85.71 |      100 |    95.24 |             30 |
  conflicter.js        |     93.1 |    91.67 |      100 |     93.1 |  77,78,174,175 |
  deprecate.js         |      100 |      100 |      100 |      100 |                |
  prompt-suggestion.js |    98.57 |    97.62 |      100 |    98.55 |             56 |
  storage.js           |    96.67 |      100 |    88.89 |    96.67 |             58 |
-----------------------|----------|----------|----------|----------|----------------|
All files              |    92.01 |     84.4 |    88.24 |    92.28 |                |
-----------------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 92.01% ( 553/601 )
Branches     : 84.4% ( 238/282 )
Functions    : 88.24% ( 45/51 )
Lines        : 92.28% ( 550/596 )
================================================================================
[16:56:58] 'test' errored after 2.26 s
[16:56:58] Error in plugin 'gulp-mocha'
Message:
    8 tests failed.
```

</details>

**Comment by al-k21** [comment] 2017-08-29 10:54
@addyosmani do you know why is it failing ?

**Comment by targos** [comment] 2017-08-29 11:27
This fails with 8.0.0 and passes with 7.10.1. Some semver-major commit must be the cause.

**Comment by targos** [comment] 2017-08-29 12:12
It seems to be linked to `domain`. Here is the stack:
```
    at Runner.uncaught (/home/mzasso/git/forks/yeoman-generator/node_modules/mocha/lib/runner.js:720:5)
    at Domain.handleException (/home/mzasso/git/forks/yeoman-generator/node_modules/gulp-mocha/index.js:44:12)
    at emitOne (events.js:115:13)
    at Domain.emit (events.js:210:7)
    at Dummy.emit (events.js:180:14)
    at Dummy.option (/home/mzasso/git/forks/yeoman-generator/lib/index.js:9:6959)
    at addWrongOp (/home/mzasso/git/forks/yeoman-generator/test/base.js:680:19)
    at tryBlock (assert.js:582:5)
    at innerThrows (assert.js:601:18)
```

When the Error is emitted by the generator, it is expected to bubble up to the `tryBlock` of `assert.throws()`.
Instead it is intercepted by `gulp-mocha`.

**Comment by targos** [comment] 2017-08-29 12:23
The solution is to upgrade `gulp-mocha`. I opened a PR: https://github.com/yeoman/generator/pull/1034

**Comment by MylesBorins** [comment] 2017-09-11 08:30
Skipping this until they can publish a fix

**Comment by SBoudrias** [comment] 2017-09-12 14:21
Latest master is fixed on our side. Thanks for following up with us!

**Comment by MylesBorins** [comment] 2017-09-12 14:42
Lovely! Let us know when you publish a new release and we'll add yeoman back into the mix

**Comment by SBoudrias** [comment] 2017-09-12 14:54
@MylesBorins Already done, 2.0.0 is out.

**Closed** 2017-09-12 17:35 UTC
