### ISSUE TITLE
Failures on all platforms?

### ISSUE THREAD

**Issue by ronag** [nodejs/citgm#785] opened 2020-02-24 07:19 UTC
citgm.eslint-plugin-jest-v23.8.0
citgm.resolve-v1.15.1

Seems to have started to fail on all platforms.

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2279/
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2280/
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2278/

master run:

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2281/ (running)

**Comment by ronag** [comment] 2020-02-24 07:26
Seems to be caused by https://github.com/nodejs/node/pull/31625

**Comment by guybedford** [comment] 2020-02-24 10:35
I'm looking into this now.

**Comment by guybedford** [comment] 2020-02-24 10:55
So far, only the eslint-plugin-jest failure seems to be caused by #31625. I'm looking into the root cause still.

For the resolve case, it is doing `require('module').builtinModules.forEach(m => require(m))` and seeing that `require('fs/promises')` is failing in its own implementation. This seems like an implementation failure in resolve itself since the addition of `fs/promises`, and can be ignored. (cc @ljharb, @devsnek)

**Comment by guybedford** [comment] 2020-02-24 11:20
I can confirm that the eslint-plugin-jest failure is not #31625 either.

Rather, it is due to this bug which was patched on the Babel helper - https://github.com/babel/babel/pull/11006.

**Comment by ljharb** [comment] 2020-02-24 15:48
It’s a known failure in resolve until the next version of resolve is released; it can’t be released until fs/promises has a known version number it will be released in.

If that’s *definitely* going to be v14.0.0, i can fix it sooner than the actual v14 release.

**Comment by RSickenberg** [comment] 2020-03-05 14:37
Hello, I have this issue with Babel-loader.

```
ERROR in ./resources/js/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/<REDACTED>/<REDACTED>/<REDACTED>/<REDACTED>/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/<REDACTED>/Projects/<REDACTED>l/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.10.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.2
3 info using node@v13.10.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle <REDACTED>@~predev: <REDACTED>@
6 info lifecycle <REDACTED>@~dev: <REDACTED>@
7 verbose lifecycle <REDACTED>@~dev: unsafe-perm in lifecycle true
8 verbose lifecycle <REDACTED>@~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/<REDACTED>/Projects/<REDACTED>/<REDACTED>/node_modules/.bin:/Users/<REDACTED>/.rvm/gems/ruby-2.2.7/bin:/Users/<REDACTED>/.rvm/gems/ruby-2.2.7@global/bin:/Users/<REDACTED>/.rvm/rubies/ruby-2.2.7/bin:/Users/<REDACTED>/.pyenv/bin:/Users/<REDACTED>/.local/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/<REDACTED>/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/romainsickenberg/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/<REDACTED>/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/<REDACTED>/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/<REDACTED>/.antigen/bundles/zsh-users/zsh-completions:/Users/<REDACTED>/.antigen/bundles/alexrochas/zsh-git-semantic-commits:/Users/<REDACTED>/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/<REDACTED>/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colorize:/Users/<REDACTED>/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker:/Users/<REDACTED>/.rvm/bin:/Users/<REDACTED>/Library/Python/3.8/bin:/Users/<REDACTED>/.composer/vendor/bin/
9 verbose lifecycle <REDACTED>@~dev: CWD: /Users/<REDACTED>/Projects/<REDACTED>/<REDACTED>
10 silly lifecycle <REDACTED>@~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle <REDACTED>@~dev: Returned: code: 2  signal: null
12 info lifecycle <REDACTED>@~dev: Failed to exec dev script
13 verbose stack Error: <REDACTED>@ dev: `npm run development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:316:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:316:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid <REDACTED>@
15 verbose cwd /Users/<REDACTED>/Projects/<REDACTED>/<REDACTED>
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/Cellar/node/13.10.1/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v13.10.1
19 verbose npm  v6.14.2
20 error code ELIFECYCLE
21 error errno 2
22 error <REDACTED>@ dev: `npm run development`
22 error Exit status 2
23 error Failed at the <REDACTED>@ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

Regards,
Romain

**Comment by targos** [comment] 2021-03-07 11:24
Closing as I think this is resolved. We can reopen a new issue if it's not.

**Closed by targos** 2021-03-07 11:24 UTC
