### ISSUE TITLE
Suggestion to improve comparing baseline to system-under-test

### ISSUE THREAD

**Issue by phestermcs** [nodejs/citgm#232] opened 2016-11-22 17:10 UTC
Just wondering if this might get consensus, as I would be willing to contribute to its implementation if so.

I'm new to citgm usage, but my understanding is it's meant to expose breakage from one version of node to the next, before it's meant to provide isolated results of a specific module's tests on a specific version of node.

In other words, I don't really care if a module's tests pass or fail, rather I care much more about them passing or failing in exactly the same way between two versions of node.

Right now I need to run a baseline test against a known version of node, like a release version, then run the same tests against my system-under-test, and then compare the results. This is cumbersome. 

It also increases the probability that any nondeterminism in the module's tests will muddy the waters in determining whether or not a test failed as a result of a change in behavior in the system-under-test, simply because the tests were ran at different times; i.e. network availability changing between test runs, etc.

What I would prefer is citgm do this for me, and only inform me in great detail of when there's a difference. I would like to be able to tell citgm "use this version of node for baseline, that version as under-test" rather than citgm using just whatever node is resolved from PATH. I would then like citgm to run a module's tests on both versions at the same time, to minimize chance of nondeterminism skewing there differences, and then only spit out silly detail when there's a difference.

Would anyone else like the same thing?

**Comment by GeorgeAdams95** [comment] 2016-11-22 17:48
@phestermcs Is this not what citgm-all does? As in we expect the tests in the lookup to pass and we can mark them flaky if they fail on a certain release. If a module fails on citgm-all then it is safe to assume that it didn't fail on the previous release

**Comment by phestermcs** [comment] 2016-11-22 17:59
Uhmm.. when I run `citgm-all` on the released v7.1.0, I'm seeing failures from the tests of specific modules. I know some of the module's tests are fundamentally nondeterministic because they may access the network, for example the tests for the `request` module. If I unplugged my network cable, then the test results between two test-runs against the _same_ version of node would differ, so I'm confused as to how 

>If a module fails on citgm-all then it is safe to assume that it didn't fail on the previous release

can be guaranteed?

**Comment by GeorgeAdams95** [comment] 2016-11-22 18:03
If you are seeing modules failures then I suggest that you make issues with specific module details and I can try to either fix them or mark them as flaky.

With regard to your second comment: Citgm tries to mark all failures as flaky or rectify them but we rely on the community to inform us of new errors creeping in.

**Comment by phestermcs** [comment] 2016-11-22 18:04
How does `citgm-all` guarantee that all the test's of a given module@version will always be deterministic between executions?

Also, I've `citgm-all` and I've seen cases where just the module installed failed on one test run, and not the next? I should note I've been running `citgm-all` concurrently on one machine, which may not be supported.

As I said, still new to `citgm`; i.e. I don't yet know what I'm doing! ;)

**Comment by GeorgeAdams95** [comment] 2016-11-22 18:04
Theoretically you should be able to use citgm-all on any machine/node release and get a clean result but this isn't always the case as new failures occur

**Comment by phestermcs** [comment] 2016-11-22 18:10
I could see that process being generally reliable if a module's tests where guaranteed to be deterministic 100% of the time, and that a used modules@version's tests where then guaranteed to never fail 100% of the time. But that would seem hard, as it seems the need to mark modules as 'flaky' at times, and that issues have be created to fix.

It was just a suggestion, as I what I'm really wanting to test is that two versions of node behave exactly the same, and maybe it's just me but I would have more confidence in that using the process I suggested.

**Comment by GeorgeAdams95** [comment] 2016-11-22 18:12
@TheAlphaNerd what do you think about this?

**Comment by gibfahn** [comment] 2016-11-22 18:31
@phestermcs So you're saying that many of the tests require a network connection?

If citgm is failing intermittently then we should start by fixing the tests (or marking them as flaky). We haven't yet had to use a baseline because we've managed to get consistent results by doing that.

The only argument against using the run twice and compare against baseline approach is that if tests are simply flaky then you can't really trust that any differences are actually caused by your change, so you're not necessarily any better off than you would be if you just assumed any failure was bad.

I'm not saying this is definitely not something we want btw, and ideas for CitGM are great! Just trying to think it through.

**Comment by gibfahn** [comment] 2016-11-22 18:34
Basically I'm not sure you can ever really get away from having random failures and then having to triage them to see whether they're due to your change (e.g. different node version). And I'm not sure whether the "run twice and use the first run as a baseline" approach would offer substantial benefit.

I guess it would be useful if there were a lot of consistent failures due to environment, i.e. something always fails on this box, so you can use the diffing approach and just ignore the failures. I'm not sure how common that use case is though, usually you'd either fix the box or fix the test.

**Comment by phestermcs** [comment] 2016-11-22 18:58
I wasn't meaning to imply any tests are using a network connection, but rather, that I know some could, which means they're fundamentally nondeterministic, I also know some tests have timeouts which is also a path to nondeterminism, and I'm sure there may be others.

I think both approaches offer different benefits, and with both being used as the most ideal.

You are correct that comparing baseline to system-under-test doesn't necessarily mean everything's hunky-dory, but if we're already in the world of using 'flaky' tests to test things, we'd just need to ensure they're deterministicly flaky on the same versions of things. If we can't at least ensure that, then is the test even valid?

My approach presumes that tests are deterministic in how they pass/fail, and by running the same tests, at the same time, on two different versions, and outputting when the results are different in the number of pass/fails, is the quickest way to locate a change, with the lowest probability of any nondeterminism skewing the comparison.

As I said, just starting to use `citgm`, still learning what to expect from it. :)

**Comment by phestermcs** [comment] 2016-11-22 19:49
I should mention again that I'm still new at using citgm, and I've be seeing differing pass/fails against the same versions of thing from different test runs, but I've been running citgm concurrently which I think was the cause. Still confirming exactly why.

**Comment by TheAlphaNerd** [comment] 2016-11-22 22:17
I'm going to close this issue but feel free to continue the conversation. 

there is no need to run a "baseline",  this would only cause citgm to take twice as long. I believe there are some modules that made changes that are currently broken, and will be following up with the maintainers to fix them. 

we basically assume that citgm always is green. if something fails we can them research to figure out if that failure was platform or version specific.

**Closed by TheAlphaNerd** 2016-11-22 22:17 UTC

**Comment by phestermcs** [comment] 2016-11-22 22:35
@TheAlphaNerd I assumed a single module's test could be ran concurrently against both a baseline and system-under-test, so test duration would be about the same.

I have no sense as to the frequency of how often module test's fail for reasons having nothing to do with a `node` version under test. Can you give me and idea of how often, on failures, one might expect to spend time having to first figure out if the failure is from the test, or a broken `node`, and then how long it usually takes to work with module authors to eventually get a fixed test back in use by citgm? I'd hate to be doing that more often than not.

**Comment by phestermcs** [comment] 2016-11-22 22:39
Right now there are 7 modules failing when ran against the v7.1.0 release. The only way I was able to know those failures had nothing to do with my system-under-test was to run a baseline and compare. Hence my opening this issue.

Is my understanding correct I should create several issues for each failure, and wait for eventual fixes? Or, how do you recommend I best deal with the failures in my testing process?

thx

**Comment by TheAlphaNerd** [comment] 2016-11-22 22:50
@phestermcs here is a run of 7.2 on our infra, the only failures are ember-cli

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/454/testReport/

If you want to open a single issue with your results from 7.1 please feel free to post the results of `citgm-all` using the Markdown reporter.

citgm has been designed with a minimal philosophy in mind from the get go. Over 90% of failures that we see have been due to changes in the module, this baseline approach would not help with those. The amount of time and work it takes to locally test after discovering a failure is fairly minimal compared to the time it would take to re run `npm install && npm test` on every repo.

/cc @jasnell to confirm if I am being reasonable here

**Comment by phestermcs** [comment] 2016-11-22 23:06
@TheAlphaNerd Thanks for your time.

I can create an issue on 7.1, but it's of little value to me directly, as `citgm` worked spectacularly in confirming my changes didn't break 7.1 behavior, but only because if the approach I took. Would you still want this? (I'm obviously a bit ignorant as to what `citgm` was meant for, but it worked great in my case). Regarding the markdown output, would I still need to set -v to silly?

If you could provide some more insight? those 90% failures, did they always fail deterministically? I mean, it's important that module tests pass when testing the module, but for my needs I'm testing to see if node itself has changes in its behavior between two versions, and all I want is gobs of things to throw at each to see if there's any difference. and then to only see lots of detail on what was actually different.

**Comment by phestermcs** [comment] 2016-11-22 23:19
@TheAlphaNerd I'm sorry I was bothering you, I will try to figure this stuff out on my own.

**Comment by phestermcs** [comment] 2016-11-22 23:34
@TheAlphaNerd If it means anything to you (as its coming across you'd prefer I go away)

I need to prove that some changes I would like to see in `node` work across a lot of the ecosystem without breaking things. I have access to lots of high end VMs. My intention is to take the top 500 or 1000 modules or more if I can from `npmjs.org`, and let the servers run for hours or days or whatever, so I can create a huge amount of real evidence I didn't break node.

There's no way I'm going to be able to work with all those authors to make sure all there tests pass, and I don't believe that's quite necessary for what I'm wanting to do. I just need tons and tons of deterministic behavior.

Can you forgive me?

**Comment by TheAlphaNerd** [comment] 2016-11-22 23:44
@phestermcs why could you not run citgm-all twice? Once with the base line, and once with the new commit? You could then diff the results.

Keep in mind, as an aside, that each of the modules you are hoping to test are going to need to be manually checked to ensure that they work on the baseline to begin with. This may be the context you are missing. By default citgm uses the npm package. But for every module in the official lookup we grab the tarball from github. Many modules do not work in citgm out of the box, and it has required working with the module maintainers to get things working.

As such, every module that is in the lookup can be assumed to be working, and it is only when things break that we need to do analysis.

I think if you attempt to just add the top 500 or 1000 modules you are going to find there is a extraodinary amount of work required just to get them running in the first place.

**Comment by phestermcs** [comment] 2016-11-23 01:03
@TheAlphaNerd 

>could you not run citgm-all twice?

I did in fact run citgm-all twice, but just to minimize any nondeterminism that is anyway related to the same test running at different times, I would have more confidence if the same test ran on both versions at the same time.

>to ensure that they work on the baseline to begin with

I think our definitions of 'work' are different in this case. I'm agreeing with you that having a module whose test's pass as defined by the author is an ideal thing, but I'm more interested in lots of determinism, regardless if a person ascribes a pass or fail meaning to it. 

I'm trying to uncover differences in behavior between two versions of node, as opposed to trying to find semantically correct behavior, by throwing as much deterministic behavior at both versions as I can, and if necessary running the same code multiple times to statistically make any nondeterminism irrelevant.

If I ran the tests from say 10000 different modules on different versions of node, and regardless if the tests always passed or failed or whatever, if the results where identical between the two versions, would you be inclined to believe they probably behaved the same? And that doesn't mean I would stop running all the current `citgm-all` tests, in fact I would like to think my efforts might in someway uncover more that could be likely candidates for inclusion.

### Your hands on experience
I would certainly appreciate the benefit of your experience, but I'm looking at the problem a little differently I think. And again having perfectly working tests could only help, but I will have to see how important that actually is with the approach I'd like to take.

>you are going to find there is a extraodinary amount of work required just to get them running

Can you help me understand what types of effort were necessary, and what you mean by 'running'? Does that mean the author had no tests, or that they didn't work when being controlled through `citgm`, or what does that mean exactly?

Regarding my other issue that was closed regarding concurrency, it was important I understand so I can know if I should provision say 256 single core machines, or 8 32 core machines, for example.
