### ISSUE TITLE
Deprecate Custom Scripts

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#301] opened 2017-01-04 20:29 UTC
This is not being used at all by the project and introduces some fragile code for cross platform support.

This would involve dropping the optional third argument `[script]` in `citgm` as well as support for specifying a custom script in the lookup.

I think this could be one of a handful of changes we can make in a new semver major. I'm going to make a milestone

**Comment by gdams** [comment] 2017-01-09 08:13
I agree that this would be a logical step, providing support for custom test scripts complicates platform support for windows hugely 3

**Comment by bzoz** [comment] 2017-01-10 13:59
Can we have some sort of support for custom scripts? For example let it only be a node.js script, it would fix platform issues.

The problem is running tests on Windows as discussed here: https://github.com/nodejs/citgm/issues/246. Having all modules `npm test` work on Windows would be perfect, but it will take some time to make it happen. In the meantime some form of `script` would be helpful..

**Comment by gdams** [comment] 2017-01-10 14:21
I personally feel that the windows problems aren't exactly our problem, citgm cannot provide tailored support for every module. We should perhaps spend more time working with the failing modules to try and add support.

**Comment by gibfahn** [comment] 2017-01-11 15:07
I think the best way to deal with this is to start going through the failing modules, working out how to fix the `npm test` command in the package.json, and then see how we go. I'm hoping that the vast majority of the issues can be fixed with a 1 line update to the `package.json`. If so then we won't need the script option.

If the entire test suite is *nix only (doesn't work with Windows) then I suspect it won't just be a case of  passing in a `script` variable.

**Comment by gibfahn** [comment] 2017-01-11 15:09
@bzoz I suspect that the vast majority of the packages will require the same fixes, as I assume most packages are doing something along the lines of `mocha/tap/tape/jasmine test/**/*.js`.

**Comment by bzoz** [comment] 2017-01-17 15:24
Fixing the modules itself is the best solution, but I'm afraid that we will find difficulties. Making one command run on all systems will be tricky, etc.

This is why I would like to have some form of `script` available as a backup.

**Comment by gibfahn** [comment] 2017-01-17 16:06
@bzoz I agree that it'll be tricky, but I don't understand under what conditions a script will be any easier than an equivalent change in the module `package.json`.

**Comment by gdams** [comment] 2017-02-07 20:48
so here's what I feel, we have marked all the appropriate windows modules as flaky/skip and so I don't really see removing custom scripts as being an issue. We can obviously work with the modules that don't support windows to try and sort that out. @bzoz what do you think?

**Closed** 2017-02-28 09:44 UTC
Labels: Semver Major
